-- ============================================================
-- CUSTOMER SHOPPING BEHAVIOR ANALYSIS — SQL Portfolio Project
-- ============================================================
-- Database: PostgreSQL (customer_trends)
-- Source Table: customer (3,900 records loaded via Python)
-- Skills: Schema Normalization, JOINs, CTEs, Window Functions,
--         Subqueries, CASE WHEN, RANK/DENSE_RANK, NTILE
-- ============================================================


-- ============================================================
-- PART 1: NORMALIZING THE DATA
-- ============================================================
-- The Python notebook loads a flat CSV into a single "customer"
-- table. Here we normalize it into 3 relational tables to
-- demonstrate proper database design.


-- Products table: one row per unique item
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

CREATE TABLE products (
    product_id   SERIAL PRIMARY KEY,
    item_name    VARCHAR(50) NOT NULL,
    category     VARCHAR(30) NOT NULL
);

INSERT INTO products (item_name, category)
SELECT DISTINCT item_purchased, category
FROM customer;


-- Customers table: one row per unique customer
CREATE TABLE customers (
    customer_id         INT PRIMARY KEY,
    age                 INT,
    gender              VARCHAR(10),
    location            VARCHAR(50),
    subscription_status VARCHAR(5),
    payment_method      VARCHAR(20),
    frequency           VARCHAR(20)
);

INSERT INTO customers (customer_id, age, gender, location,
                       subscription_status, payment_method, frequency)
SELECT DISTINCT ON (customer_id)
       customer_id, age, gender, location,
       subscription_status, payment_method, frequency_of_purchases
FROM customer;


-- Orders table: each row is a transaction, linked by foreign keys
CREATE TABLE orders (
    order_id         SERIAL PRIMARY KEY,
    customer_id      INT REFERENCES customers(customer_id),
    product_id       INT REFERENCES products(product_id),
    purchase_amount  NUMERIC(10,2),
    size             VARCHAR(5),
    color            VARCHAR(20),
    season           VARCHAR(10),
    review_rating    NUMERIC(3,1),
    shipping_type    VARCHAR(20),
    discount_applied VARCHAR(5),
    promo_code_used  VARCHAR(5),
    previous_purchases INT
);

INSERT INTO orders (customer_id, product_id, purchase_amount, size,
                    color, season, review_rating, shipping_type,
                    discount_applied, promo_code_used, previous_purchases)
SELECT c.customer_id,
       p.product_id,
       c.purchase_amount,
       c.size,
       c.color,
       c.season,
       c.review_rating,
       c.shipping_type,
       c.discount_applied,
       c.promo_code_used,
       c.previous_purchases
FROM customer c
JOIN products p ON c.item_purchased = p.item_name AND c.category = p.category;


-- ============================================================
-- PART 2: CORE ANALYTICS (Q1–Q10)
-- ============================================================


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT c.gender,
       COUNT(o.order_id)              AS total_orders,
       SUM(o.purchase_amount)         AS total_revenue,
       ROUND(AVG(o.purchase_amount), 2) AS avg_order_value
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.gender
ORDER BY total_revenue DESC;


-- Q2. Which customers used a discount but still spent more than
--     the average purchase amount?
SELECT c.customer_id,
       c.gender,
       c.location,
       o.purchase_amount
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
WHERE o.discount_applied = 'Yes'
  AND o.purchase_amount >= (SELECT AVG(purchase_amount) FROM orders)
ORDER BY o.purchase_amount DESC;


-- Q3. Which are the top 5 products with the highest average review rating?
--     (Only products with at least 10 purchases for statistical reliability)
SELECT p.item_name,
       p.category,
       COUNT(o.order_id)                       AS total_purchases,
       ROUND(AVG(o.review_rating::NUMERIC), 2) AS avg_rating
FROM products p
JOIN orders o ON p.product_id = o.product_id
GROUP BY p.item_name, p.category
HAVING COUNT(o.order_id) >= 10
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Compare average purchase amounts across all shipping types.
SELECT o.shipping_type,
       COUNT(o.order_id)                    AS total_orders,
       ROUND(AVG(o.purchase_amount), 2)     AS avg_amount,
       ROUND(STDDEV(o.purchase_amount), 2)  AS stddev_amount
FROM orders o
GROUP BY o.shipping_type
ORDER BY avg_amount DESC;


-- Q5. Do subscribed customers spend more? Compare average spend and
--     total revenue between subscribers and non-subscribers.
SELECT c.subscription_status,
       COUNT(DISTINCT c.customer_id) AS total_customers,
       COUNT(o.order_id)             AS total_orders,
       ROUND(AVG(o.purchase_amount), 2) AS avg_spend,
       ROUND(SUM(o.purchase_amount), 2) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.subscription_status
ORDER BY total_revenue DESC;


-- Q6. Which 5 products have the highest percentage of purchases
--     with discounts applied?
SELECT p.item_name,
       p.category,
       COUNT(o.order_id) AS total_orders,
       ROUND(
           100.0 * SUM(CASE WHEN o.discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*), 2
       ) AS discount_pct
FROM products p
JOIN orders o ON p.product_id = o.product_id
GROUP BY p.item_name, p.category
ORDER BY discount_pct DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on
--     previous purchases and compare their spending behavior.
WITH customer_segments AS (
    SELECT c.customer_id,
           c.gender,
           o.previous_purchases,
           o.purchase_amount,
           CASE
               WHEN o.previous_purchases <= 1  THEN 'New'
               WHEN o.previous_purchases <= 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
)
SELECT customer_segment,
       COUNT(*)                            AS total_customers,
       ROUND(AVG(purchase_amount), 2)      AS avg_spend,
       ROUND(SUM(purchase_amount), 2)      AS total_revenue
FROM customer_segments
GROUP BY customer_segment
ORDER BY total_revenue DESC;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT p.category,
           p.item_name,
           COUNT(o.order_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY p.category
               ORDER BY COUNT(o.order_id) DESC
           ) AS item_rank
    FROM products p
    JOIN orders o ON p.product_id = o.product_id
    GROUP BY p.category, p.item_name
)
SELECT item_rank, category, item_name, total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9. Are repeat buyers (>5 previous purchases) more likely to subscribe?
SELECT c.subscription_status,
       COUNT(DISTINCT c.customer_id) AS repeat_buyers,
       ROUND(
           100.0 * COUNT(DISTINCT c.customer_id)
           / SUM(COUNT(DISTINCT c.customer_id)) OVER (), 2
       ) AS pct_of_repeat_buyers
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
WHERE o.previous_purchases > 5
GROUP BY c.subscription_status;


-- Q10. Revenue contribution by age group (derived using CASE WHEN)
--      with percentage of total revenue.
SELECT
    CASE
        WHEN c.age < 25             THEN '18-24'
        WHEN c.age BETWEEN 25 AND 34 THEN '25-34'
        WHEN c.age BETWEEN 35 AND 44 THEN '35-44'
        WHEN c.age BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+'
    END AS age_group,
    COUNT(o.order_id)                      AS total_orders,
    ROUND(SUM(o.purchase_amount), 2)       AS total_revenue,
    ROUND(
        100.0 * SUM(o.purchase_amount)
        / SUM(SUM(o.purchase_amount)) OVER (), 2
    ) AS revenue_pct
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY age_group
ORDER BY total_revenue DESC;


-- ============================================================
-- PART 3: ADVANCED ANALYTICS (Q11–Q15)
-- ============================================================


-- Q11. Seasonal revenue trends — which season drives the most sales
--      per category?
WITH seasonal_sales AS (
    SELECT p.category,
           o.season,
           ROUND(SUM(o.purchase_amount), 2)  AS total_revenue,
           COUNT(o.order_id)                 AS total_orders,
           DENSE_RANK() OVER (
               PARTITION BY p.category
               ORDER BY SUM(o.purchase_amount) DESC
           ) AS season_rank
    FROM products p
    JOIN orders o ON p.product_id = o.product_id
    GROUP BY p.category, o.season
)
SELECT category, season, total_revenue, total_orders, season_rank
FROM seasonal_sales
WHERE season_rank = 1
ORDER BY total_revenue DESC;


-- Q12. Cumulative revenue by age group — running total analysis.
WITH age_revenue AS (
    SELECT
        CASE
            WHEN c.age < 25             THEN '18-24'
            WHEN c.age BETWEEN 25 AND 34 THEN '25-34'
            WHEN c.age BETWEEN 35 AND 44 THEN '35-44'
            WHEN c.age BETWEEN 45 AND 54 THEN '45-54'
            ELSE '55+'
        END AS age_group,
        ROUND(SUM(o.purchase_amount), 2) AS total_revenue
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY age_group
)
SELECT age_group,
       total_revenue,
       SUM(total_revenue) OVER (ORDER BY total_revenue DESC) AS cumulative_revenue,
       ROUND(
           100.0 * SUM(total_revenue) OVER (ORDER BY total_revenue DESC)
           / SUM(total_revenue) OVER (), 2
       ) AS cumulative_pct
FROM age_revenue
ORDER BY total_revenue DESC;


-- Q13. Top 25% high-value customers using NTILE quartile analysis.
WITH customer_spend AS (
    SELECT c.customer_id,
           c.gender,
           c.location,
           c.subscription_status,
           ROUND(AVG(o.purchase_amount), 2) AS avg_spend,
           COUNT(o.order_id)                AS total_orders,
           NTILE(4) OVER (ORDER BY AVG(o.purchase_amount) DESC) AS spend_quartile
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.gender, c.location, c.subscription_status
)
SELECT customer_id, gender, location, subscription_status,
       avg_spend, total_orders
FROM customer_spend
WHERE spend_quartile = 1
ORDER BY avg_spend DESC
LIMIT 20;


-- Q14. Payment method preference by gender — cross-tabulation with
--      percentage breakdown within each gender.
SELECT c.gender,
       c.payment_method,
       COUNT(o.order_id)                     AS total_orders,
       ROUND(SUM(o.purchase_amount), 2)      AS total_revenue,
       ROUND(AVG(o.purchase_amount), 2)      AS avg_order_value,
       COALESCE(
           ROUND(
               100.0 * COUNT(o.order_id)
               / NULLIF(SUM(COUNT(o.order_id)) OVER (PARTITION BY c.gender), 0), 2
           ), 0
       ) AS pct_within_gender
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.gender, c.payment_method
ORDER BY c.gender, total_orders DESC;


-- Q15. Top 10 locations by revenue with customer count and avg rating.
SELECT c.location,
       COUNT(DISTINCT c.customer_id)           AS unique_customers,
       COUNT(o.order_id)                       AS total_orders,
       ROUND(SUM(o.purchase_amount), 2)        AS total_revenue,
       ROUND(AVG(o.purchase_amount), 2)        AS avg_order_value,
       ROUND(AVG(o.review_rating::NUMERIC), 2) AS avg_rating
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.location
HAVING COUNT(o.order_id) >= 5
ORDER BY total_revenue DESC
LIMIT 10;
